# SonarQube Configuration — DevOps Lab 6
sonar.projectKey=devops-lab6
sonar.projectName=DevOps Lab 6 — Student API
sonar.projectVersion=1.0.0

# Source code
sonar.sources=.
sonar.exclusions=node_modules/**,newman-report.json,zap-report.html

# Language
sonar.language=js
sonar.sourceEncoding=UTF-8

# Server
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=sonar123
