# ============================================
# Ansible Inventory — DevOps Lab 4
# ============================================

# Group: Web Servers
[webservers]
web-server-1 ansible_host=localhost ansible_port=2201
web-server-2 ansible_host=localhost ansible_port=2202

# Group: Database Servers
[dbservers]
db-server-1  ansible_host=localhost ansible_port=2203

# Group: All Production Servers
[production:children]
webservers
dbservers

# Global Variables
[all:vars]
ansible_user=root
ansible_password=root
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
